export const GET_CONTENT = "GET_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const ADD_TO_READING_HISTORY = "ADD_TO_READING_HISTORY";

//* filter action

export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const TOGGLE_TAG_FILTER = "TOGGLE_TAG_FILTER";
export const CLEAR_TAG_FILTER = "CLEAR_TAG_FILTER";
